# .github/workflows/gradle-build-pr.yml
name: Build PMM
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: test
      run: echo ${{ github.ref }}
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11.0.5
    - name: Build PMM with gradle
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: ./ParadoxosGameModManager
        build-root-directory: ./ParadoxosGameModManager
        arguments: dist
#    - name : Upload produced bin
#      uses: actions/upload-artifact@v1
#      with:
#        name: ${{ env.BUILD_ARTIFACT_NAME }}
#        path: ${{ env.BUILD_ARTIFACT_PATH }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.BUILD_ARTIFACT_PATH }}
        asset_name: ${{ env.BUILD_ARTIFACT_NAME }}.zip
        tag: indev
        overwrite: true
